apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  containers:
    - name: debug
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]  # śpij godzinę, żebyśmy mogli wejść
      volumeMounts:
        - name: data
          mountPath: /data              # tu pojawi się zawartość PVC
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: job-results-pvc      # <-- NAZWA TWOJEGO PVC